"""
Django settings for rincart project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost','https://ms0724v4-8000.inc1.devtunnels.ms/']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rincartapp',
    # Required for allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    
    # The Google provider
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
]

SITE_ID = 1

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Google OAuth specific settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}

# Automatically log the user in without showing intermediate "Are you sure you want to sign in?" pages
SOCIALACCOUNT_LOGIN_ON_GET = True

# Skips the extra signup form for social accounts if Google already gives us their email/username
SOCIALACCOUNT_AUTO_SIGNUP = True

# 1. Skip the "Are you sure you want to sign out?" ugly page
ACCOUNT_LOGOUT_ON_GET = True

# 2. Where to send them immediately after logging out (the home page)
ACCOUNT_LOGOUT_REDIRECT_URL = '/'


# Crucial Workflow Redirects
# 1. If it's a completely new user, django-allauth can send them to a signup/onboarding step
ACCOUNT_SIGNUP_REDIRECT_URL = '/auth/continue-setup/'

# 2. If they are an existing user just logging back in
LOGIN_REDIRECT_URL = '/'



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rincart.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.debug',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rincart.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


import os
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


import environ

# environ ഇൻഷിയലൈസ് ചെയ്യുന്നു
env = environ.Env()
# .env ഫയൽ റീഡ് ചെയ്യുന്നു
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

DATABASES = {
    'default': env.db(),
}

SECRET_KEY = env('SECRET_KEY')

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


CSRF_COOKIE_SECURE = False  # ഡെവലപ്‌മെന്റിൽ ഇത് False ആയിരിക്കണം
SESSION_COOKIE_SECURE = False # ഡെവലപ്‌മെന്റിൽ ഇത് False ആയിരിക്കണം


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'myproooo123@gmail.com'  # നിങ്ങളുടെ ജിമെയിൽ ഐഡി ഇവിടെ നൽകുക

# ⚠️ ശ്രദ്ധിക്കുക: ഇത് നിങ്ങളുടെ സാധാരണ പാസ്‌വേഡ് അല്ല! 
# Google Account -> Security -> 2-Step Verification -> App Passwords വഴി ഉണ്ടാക്കുന്ന 16 അക്ഷരമുള്ള കോഡ് ആണ്.
EMAIL_HOST_PASSWORD = 'clfpuwkmygemrdre' 

# ഇമെയിൽ അയക്കുമ്പോൾ ആരുടെ പേരിൽ പോകണം എന്ന് സെറ്റ് ചെയ്യാം
DEFAULT_FROM_EMAIL = 'RinCart <myproooo123@gmail.com>'
