"""
Django settings for rincart project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os
import environ

# 1. ഇവ എപ്പോഴും ഏറ്റവും മുകളിൽ ഉണ്ടായിരിക്കണം
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# 2. ഇനി നിങ്ങളുടെ ബാക്കി കോഡുകൾ താഴെ നൽകാം
SECRET_KEY = env('SECRET_KEY')

DATABASES = {
    'default': env.db(),
}

# 3. സ്റ്റാറ്റിക് സെറ്റിങ്സ് ഇതിന് താഴേക്ക് മാറ്റുക
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'localhost','rincart.onrender.com']  # 👈 render.com ൽ ഹോസ്റ്റ് ചെയ്യുമ്പോൾ നിങ്ങളുടെ ഡൊമെയ്ൻ ചേർക്കുക


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    'rincartapp',
    # Required for allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'anymail',
    # The Google provider
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    
]

SITE_ID = 1

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]



# Google OAuth specific settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}

# Automatically log the user in without showing intermediate "Are you sure you want to sign in?" pages
SOCIALACCOUNT_LOGIN_ON_GET = True

SOCIALACCOUNT_ADAPTER = 'rincartapp.adapters.MySocialAccountAdapter'
# 1. Skip the "Are you sure you want to sign out?" ugly page
ACCOUNT_LOGOUT_ON_GET = True

# 2. Where to send them immediately after logging out (the home page)
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'

# സോഷ്യൽ ലോഗിൻ ചെയ്യുമ്പോൾ യൂസർനെയിം ഓട്ടോമാറ്റിക് ആയി ജനറേറ്റ് ചെയ്യാൻ (Email-ൽ നിന്ന്)
SOCIALACCOUNT_AUTO_SIGNUP = True
# Crucial Workflow Redirects
# 1. പുതിയ യൂസർ ഗൂഗിൾ വഴി വരുമ്പോൾ നേരെ OTP വെരിഫിക്കേഷൻ പേജിലേക്ക് വിടുക
ACCOUNT_SIGNUP_REDIRECT_URL = '/verify-otp/'  # (നിങ്ങളുടെ OTP യുആർഎൽ എന്താണോ അത് നൽകുക)

# 2. പഴയ യൂസർ വീണ്ടും ലോഗിൻ ചെയ്യുമ്പോഴും സുരക്ഷയ്ക്ക് വേണ്ടി OTP പേജിലേക്ക് തന്നെ വിടുക
LOGIN_REDIRECT_URL = '/verify-otp/'



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sites.middleware.CurrentSiteMiddleware',
]

ROOT_URLCONF = 'rincart.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.debug',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rincart.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases




# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


CSRF_COOKIE_SECURE = False  # ഡെവലപ്‌മെന്റിൽ ഇത് False ആയിരിക്കണം
SESSION_COOKIE_SECURE = False # ഡെവലപ്‌മെന്റിൽ ഇത് False ആയിരിക്കണം


MEDIA_URL = '/media/'

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}


EMAIL_BACKEND = "anymail.backends.brevo.EmailBackend"
DEFAULT_FROM_EMAIL = "RinCart Official <rincartofficial@gmail.com>" # 👈 നിങ്ങളുടെ ഇമെയിൽ

ANYMAIL = {
    "BREVO_API_KEY": env("BREVO_API_KEY"),
}

