# Generated by Django 6.0.6 on 2026-07-04 08:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer Query',
                'verbose_name_plural': 'Customer Queries',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('original_price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('category', models.CharField(choices=[('fashion', 'Fashion & Dresses'), ('mobile', 'Mobiles'), ('beauty', 'Beauty Products'), ('electronic', 'Electronics'), ('home_appliance', 'Home Appliances'), ('toy', 'Toys')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_cod_available', models.BooleanField(default=True, verbose_name='COD Available?')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Enter GST/Tax percentage (e.g., 1.2 for 1.2%, 0.3 for 0.3%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('color_name', models.CharField(blank=True, help_text='ഉദാ: Matt Black', max_length=50, null=True)),
                ('color_code', models.CharField(blank=True, help_text='Hex code: #000000', max_length=7, null=True)),
                ('parent_product', models.ForeignKey(blank=True, help_text='മെയിൻ പ്രൊഡക്റ്റ് ആണെങ്കിൽ ഇത് ബ്ലാങ്ക് ഇടുക. ഇതൊരു കളർ വേരിയന്റ് ആണെങ്കിൽ മെയിൻ പ്രൊഡക്റ്റ് സെലക്ട് ചെയ്യുക.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='rincartapp.product')),
                ('users_bought', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MobileSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(help_text='e.g., Snapdragon 8 Gen 3 / Apple A18 Pro', max_length=100)),
                ('chipset', models.CharField(blank=True, help_text='e.g., 4nm Octa-core', max_length=100, null=True)),
                ('ram', models.CharField(help_text='e.g., 8GB / 12GB LPDDR5X', max_length=50)),
                ('storage', models.CharField(help_text='e.g., 128GB / 256GB UFS 4.0', max_length=50)),
                ('battery', models.CharField(help_text='e.g., 5000 mAh with 67W Fast Charging', max_length=100)),
                ('camera', models.CharField(blank=True, help_text='e.g., 50MP Main + 12MP Ultra-wide', max_length=200, null=True)),
                ('display', models.CharField(blank=True, help_text='e.g., 6.7-inch AMOLED, 120Hz', max_length=150, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_specs', to='rincartapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Buying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_f_name', models.CharField(max_length=100)),
                ('customer_s_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('quantity', models.IntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('payment_method', models.CharField(choices=[('card', 'Credit / Debit Card'), ('paypal', 'PayPal'), ('upi', 'UPI / NetBanking'), ('cod', 'COD')], default='paypal', max_length=20)),
                ('del_address', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rincartapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_image', models.ImageField(blank=True, null=True, upload_to='products/additional')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='rincartapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('original_price', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='rincartapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rincartapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
